### ISSUE TITLE
📅 Publicodes: feuille de route été - automne 2020

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#1071]
La bibliothèque publicodes et le langage vont continuer d'évoluer, avec comme vision d'être une solution générique pour décrire, implémenter et documenter des calculs basés sur une source de vérité complexe (législation, impact carbone, ...).  

Les champs d'application visés sont, par exemple : la génération de simulateurs, la création de formulaire interactifs, et l'implémentation de règles issues de la loi. 

Notre but officieux : remplacer toutes les feuilles excel publiques par du publicodes.

Pour cela, il nous faut avancer dans la fiabilisation de la librairie, et dans la formalisation du langage (#796).

> **En cours de rédaction**

### Été 2020
- [x] Pouvoir accéder à la liste des dépendances pour chaque variable (#986)
- [x] Détecter les cycles lors du parsing des règles (#823)
- [x] Ajouter le mécanisme remplace dans la documentation (#765)
- [ ] Afficher les variables temporelles dans la documentation (#1069)
- [x] Clarifier le fonctionnement du mécanisme remplace (#1027 & #1081)
- [x] Changer le fonctionnement du référencement de valeurs (#1083)

### Automne 2020
- [x] Séparer le moteur coeur et le rendu de la documentation (#1070)
- [x] Clarifier et fiabiliser `rend non applicable` (#887) 
- [ ] Pouvoir gérer l'addition de jours à une date (#1007)
- [x] Simplifier et solidifier la définition des mécanisme (#1015)

### Want to do

Listons ici les choses qu'on trouve importantes et qu'on aimerait faire mais qui ne sont pas forcément pour un avenir proche. Ceci aidera à donner de la vision technique, mais aussi à débattre sur l'avenir du socle tech.

_A COMPLETER_

- Découpler l'AST de l'exécution (_issue existante à retrouver_)
- Compiler publicodes en publicodes-simple // Retirer les "mécanismes" du coeur de publicode et du parser
- Simplifier la vérification lors de l'ajout d'un nouveau simulateur (cf. #965)

**Comment by denismerigoux** [comment]
Je suis heureux de voir que votre priorité pour les mois qui viennent sera la formalisation de PubliCodes! 

Cette formalisation doit être pour vous l'occasion de prendre du recul sur le parseur et votre moteur d'exécution et vous demander de manière abstraite quels sont vos programmes et comment vous les exécuter. L'implémentation du parseur et de l'interpréteur est toujours plus aidée quand elle est guidée par la formalisation. À l'inverse, formaliser le comportement ad hoc d'un logiciel sans chercher à en dégager une cohérence interne est difficile et peu intéressant.

Je vous conseille vivement de suivre au moins un cours de niveau M1 sur la sémantique des langages de programmation avant de vous lancer dans la tâche. Sans connaître les concepts fondamentaux, vous aller devoir réinventer la roue et il est probable que vous échouiez dans votre tâche. 

L'université Paris 7 a apparemment fait un Moodle pour son cours de langages de programmation : https://moodlesupd.script.univ-paris-diderot.fr/enrol/index.php?id=6371, manuel de cours https://hal.archives-ouvertes.fr/cel-01422101v2/document.

J'aime votre objectif officieux ambitieux de remplacer les feuilles Excel de l'administration publique ! Je pense que l'objectif que je j'aimerais poursuivre idéalement est un peu différent : il s'agirait de remplacer les systèmes qui calculent actuellement les impôts, taxes, cotisations en production. Les deux objectifs sont complémentaires :)

**Comment by denismerigoux** [comment]
Autre ressource : bouquin d'introduction gratuit en moment sur le site de Springer (un peu plus accessible) https://link.springer.com/book/10.1007%2F978-3-319-70790-7

**Comment by mquandalle** [comment]
Les items de cette feuille de route ont été traités. Reste l'affichage des variables temporelles dans la documentation (#1069) mais qu'on ne fera pas car nous avons retiré cette fonctionnalité du moteur pour l'instant, ainsi que l'addition de jours à une date (#1007) qui est un retour utilisateur dont nous n'avons pas besoin sur mon-entreprise et qu'il n'est pas urgent de traiter pour l'instant.

La suite dans  #1293.
