### ISSUE TITLE
📅 Mon-entreprise : feuille de route été - automne 2020

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#1072]
Mon-entreprise a pour but d' accompagner les créateurs d’entreprise dans le développement de leur activité.

Notre objectif est de lever toutes les incertitudes vis à vis de l’administration, et de fournir des outils complets et maintenus à jour pour estimer précisément les dépenses liées aux cotisations sociales.

Dans ce but, nous allons continuer à [étendre notre couverture législative](https://github.com/betagouv/mon-entreprise/issues/1072), développer nos [offres de simulateurs](https://github.com/betagouv/mon-entreprise/projects/5), tout en améliorant et fiabilisant les simulateurs existants.

Cette feuille de route est élaborée en collaboration avec l'Acoss, elle est succeptible d'évoluer en fonction des dispositifs futurs, et de priorités nouvelles.

> **En cours de rédaction**

### Été 2020
- [x] Développer un formulaire interactif de remplissage de la demande de détachement pour les travailleurs indépendants
- [x] Développer un simulateur de revenus à destination des [practiciens et auxiliaires médicaux (PAM)](https://www.urssaf.fr/portail/home/praticien-et-auxiliaire-medical.html)
- [x] Améliorer le référencement des moteurs de recherche en implémentant les recommandations de #972   (PR #1085)
johangirod wants to merge 6 commit
- [ ] Ajouter la prime de solidarité #948
- [x] Fiabiliser l'implémentation du dispositif d'activité partielle #994 #988
- [x] Corriger le simulateur auto-entrepreneur pour les professions libérales #982 
- [x] Améliorer la gestion du temps partiel dans le simulateur #649
- [ ] Avoir des groupes de question dans le simulateur #220 
### Automne 2020
- [ ] Améliorer la page de comparaison des statuts
- [ ] Collaborer avec les antennes régionales pour l'intégration des dispositifs locaux à destination des créateur d'entreprise dans le site
- [ ] Améliorer le simulateur auto-entrepreneur #834 #531 #517
- [ ] Pouvoir partager une simulation #552
- [ ] Pouvoir spécifier une simulation sur des périodes différentes : nombre de jour, cachet, taux horaire, etc... #475
- [x] Publier les règles de mon-entreprise dans un nouveau paquet, séparé

**Comment by mquandalle** [comment]
Feuille de route complétée à un peu plus de 50%, ce qui n'est pas énorme. Mais il y a de bonnes raisons :

- Nous avons plus travaillé sur Publicodes #1071 
- La feuille de route a été rédigée rapidement, nous n'avions pas spécialement pris en compte le temps de développement sur chaque item
- Nous avons aussi travaillé sur certaines fonctionnalités qui n'avaient pas été planifiéesn, en particulier à la suite du reconfinement : intégration des aides à l'embauche, du contrat de professionnalisation, des réductions de cotisations covid, meilleure gestion des retours utilisateurs.

Voyons comment nous pouvons partager une feuille de route plus fidèle à nos travaux en cours pour le prochain trimestre (semestre ?). Et peut-être même l'afficher sur le site ?
