### ISSUE TITLE
Problèmes identifiés sur l'utilisation de Publicodes x modele-social

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#1425]
- [ ] Les warnings de type dans la console sont faux et empêche la bonne lecture des messages importants (erreurs, résultats)  #1534
- [x] Le composant <Documentation> de publicodes-react demande une prop `langage` qui ne parait pas nécessaire
- [x] La librairie `publicodes-react` de fonctionne pas en l'état (il manque un fichier dans le dossier `dist`). Il faut ajouter des tests #1484
- [x] `publicodes-react` a une dépendance à i18n qui demande une instanciation de la lib qui n'est pas explicitée.
- [ ] La pluralisation des unités n'est pas très claire, et abouti parfois à des bugs avec des unités de types `semaines/semaine` ou `heure/heures`, sans que l'on sache très bien ce qu'il y a à changer. #1350
- [x] Les définitions TS de `modele-social` ne sont pas publiées dans le package npm.

**Comment by mquandalle** [comment]
4 éléments sur 6 sont corrigés, il y a des tickets ouverts pour les 2 restants.
