### ISSUE TITLE
Checklist lancement mon-entreprise.urssaf.fr 🚀

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1829]
### Avant de merger la branche `charte-urssaf-bootstrap` sur `master`

- [x] Configuration `Netlify.toml`
    - [x] Mise à jour de l'URL dans les actions Github
    - [x] Configuration de la redirection de `mon-entreprise.fr` vers un ancien déploiement en prévision du merge sur master

### Avant de rediriger le trafic vers la nouvelle URL

- [x] Merger la branche `charte-urssaf-bootstrap`
- [x] Contrôler le fonctionnement de la version en prod, y compris intégrations iframe
- [x] Mettre à jour les logos
  - [x] Favicon ×4
  - [x] Logo principal
  - [x] Logo version mycompanyinfrance
  - [x] Balises meta open-graph
- [x] Valider le nouveau design avec la Dicom

### Mise en production

- [x] Ajouter une redirection 301 de `mon-entreprise.fr` vers `mon-entreprise.urssaf.fr`
- [x] Contrôler le fonctionnement en prod, y compris intégrations iframe
- [x] Vérifier la remontée des stats sur AT Internet
- [x] Avertir Google et Bing du changement d'URL via la search console
- [x] Mettre à jour les liens présents dans les Readme, l'URL Github, les liens du site https://publi.codes https://github.com/betagouv/publicodes/pull/135
- [x] Mettre à jour la [fiche beta.gouv](https://beta.gouv.fr/startups/mon-entreprise.html) https://github.com/betagouv/beta.gouv.fr/pull/7882
- [x] Publier Release Github
