### ISSUE TITLE
Simulateur cout de création d'entreprise

### ISSUE THREAD

**Issue by wiinxt** [betagouv/mon-entreprise#2461]
### En deux mots
Commande du cabinet ministériel pour un simulateur de cout de création, mon-entreprise s'est positionné dessus. 

Simplement, 
Coût de création = Frais de greffe + Dépôt dans un journal d'annonce légal (JAL)

### Documentation
- [ Page de l'INPI](https://formalites.entreprises.gouv.fr/tarifs.php)
- [Page de service-public](https://entreprendre.service-public.fr/vosdroits/F23282)
- [Sur les annonces légales](https://www.legalplace.fr/guides/frais-annonce-legale/)

### Précisions

- Les JAL ont une logique qui dépend beaucoup du prestataire. Les montant forfaitaires existent dans la loi, mais aucun moyen de savoir si ils sont beaucoup utilisés. Peut-être mettre une fourchette dans un premier temps (comme sur service-public) ?

  > Fun fact : la presse quotidienne régionale est financée à 50% par cette mane
- Différence entre immatriculation principale et immatriculation par création d'une entreprise  (39 vs 41) : la deuxième est une réduction de la formalité pour la création de société commerciale (pas concernée les sociétés agricole, SELARL, etc)
- Pas de JAL pour les sociétés agricoles ;
- Pas de frais de BODACC pour la création ;
- Pas de frais liés à l'INPI pour la création ;
- Uniquement frais de greffe + JAL ;
- coût HT ;
- Société civile, société agricole, SELARL, etc -> pas de réduction pour la création, seulement société commerciale et artisanale ;
- Plus de déclarations d'affectation du patrimoine d'EIRL.
- toute société doit être immatriculée au RCS

#### Bénéficiaire effectif : 
- montant à payer en plus ;
- détenir un pourcentage minimale de droit de vote ou de capital social de 25% ;
- ou si personne ne dépasse le seul, c'est le représentant ;

#### Agents commerciaux : 
- A la fois personne physique non immatriculé au RCS et société imatriculé au RCS

#### Agents commerciaux : 
- A la fois personne physique non immatriculé au RCS 

#### Frais de transmissions
- Désormais, tout est sur guichet unique, dématerialisé, donc pas de frais transmission possible
- Par contre, le greffe peut envoyer des pièces, facture débourt postaux, 0.97€ HT (à vérifier)
- Si RCS est un succès, le greffe doit vous envoyer des kbis, ces frais postaux sont inclus dans la prestation principale
- Demande de complément facturé en cas de pièce manquante chez le RCS mais pas chez les artisans. 

#### Auto-entreprise
- pas de frais de création
- plus de formation obligatoire
- frais d'immatriculation de cessation et radiation sont gratuit
**Mais**
- frais de rejet en cas de mauvaise déclaration (3 €)
    - normalement pas censé arrivé via le guichet unique
    - mais ça peut arriver pour les micro entrepreneur réglementée (hors libérale)
    - exemple : taxi

#### Autre
- Double immatriculation possible (artisan + commerçant), dans ce cas, réduction artisan

### Todo

- [x] Squelette de la page
- [x] Ajout des règles
- [ ] Ajout dans le comparateur de statut
