### ISSUE TITLE
Améliorations de la checklist à l'embauche

### ISSUE THREAD

**Issue by laem** [betagouv/mon-entreprise#284]
- [x] On noie aujourd'hui l'information de la création de société (et l'obtention Siren KBIS). Le faire dans le flux de questions et garder une check-list
- [x] Parler du Kbis qui est une carte d'identité
- [x] faire du point effectif-TESE-Paie une étape des questions. 
- [x] faire les liens FR directement en anglais avec Google translate 
- [ ] mettre l'explication de la paie (DSN+fiche de paie) comme une explication de ce que doivent produire ces logiciels 
- [ ] afficher le Siret lors de la recherche d'entreprise et corriger le libellé "adresse"
- [ ] La DPAE est dans le TESE : en parler comme les fiches de paie et la DSN, comme une explication
- [x] faire un paragraphe sur les conventions collectives et le droit du travail à la fin des questions du simulateur
- [x] intégrer la recherche de conv. coll du droit du travail numérique
- [ ] "private payslip software" 

- [x] faire les liens des branches vers des pages 

- [ ] parler de net-entreprises (notamment l'atmp) quand l'effectif est > 2
- [x] mettre la micro entreprise comme un exemple voir un choix à côté de EI 
- [x] sur le choix salarié vs indép, parler des fiches de paie
- [x] mentionner pour les personnes morales le besoin de rédiger des statuts

Globalement, je pense qu'il faut que l'on guide l'utilisateur dans un nombre très restreint de choix qui représentent les choix principalement utilisés aujourd'hui.
