### ISSUE TITLE
[RGCP] Simulateur réduction générale

### ISSUE THREAD

**Issue by JalilArfaoui** [betagouv/mon-entreprise#2910]
La réduction générale concerne certaines des cotisations patronales. Elle varie en fonction l'effectif de l'entreprise et de la rémunération des salariés.

**Besoin :** 

Reprendre le simulateur actuel du site Urssaf.fr et l'adapter aux principes d'interface utilisateur de mon-entreprise

**Source :** 
https://www.urssaf.fr/accueil/employeur/beneficier-exonerations/reduction-generale-cotisation.html
https://entreprendre.service-public.fr/vosdroits/F24542
https://boss.gouv.fr/portail/accueil/exonerations/allegements-generaux.html#titre-chapitre-1--la-reduction-general

Simulateur actuel : https://www.declaration.urssaf.fr/calcul/

```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/mon-entreprise/issues/3086
- [ ] https://github.com/betagouv/mon-entreprise/issues/3087
- [ ] https://github.com/betagouv/mon-entreprise/issues/3088
- [ ] https://github.com/betagouv/mon-entreprise/issues/3221
- [ ] https://github.com/betagouv/mon-entreprise/issues/3219
- [ ] https://github.com/betagouv/mon-entreprise/issues/3218
- [x] [RGCP] Ajouter le cas de l’application de la déduction forfaitaire spécifique
- [x] [RGCP] Calculer la réduction générale sur l'année précédente
- [ ] https://github.com/betagouv/mon-entreprise/issues/3220
- [ ] https://github.com/betagouv/mon-entreprise/issues/3251
- [ ] https://github.com/betagouv/mon-entreprise/issues/3291
```
