### ISSUE TITLE
Nouveaux parcours économie collaborative

### ISSUE THREAD

**Issue by JalilArfaoui** [betagouv/mon-entreprise#2911]
Simulateur pour assister dans les revenus économie collaborative (BlablaCar, Vinted, AirBnb…) à déclarer.
```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/mon-entreprise/issues/2915
- [ ] Simulateur Autoentrepreneur Loueur Meublé Non Professionel
- [ ] https://github.com/betagouv/mon-entreprise/issues/2917
- [ ] https://github.com/betagouv/mon-entreprise/pull/2914
```

**Comment by JalilArfaoui** [comment]
Remplacé par la milestone https://github.com/betagouv/mon-entreprise/milestone/14
