### ISSUE TITLE
Simulateur Cessation d'activité

### ISSUE THREAD

**Issue by VeroniqueR75** [betagouv/mon-entreprise#2925]
En tant que travailleur indépendant (hors autoentrepreneur et PAM)
Je veux calculer une estimation des cotisation dues pour l'année de cessation de mon activité sans inclure les dettes antérieures
Afin de connaître le montant que je dois à l'Urssaf à l'arrêt de mon activité 

**Public concerné :** 
- Travailleurs Indépendants (hors autoentrepreneurs et PAM)

**Besoin :** 

Créer un nouveau simulateur dans la rubrique "Autres outils" dont le titre est : "Estimations de cotisations à devoir après cessation" à partir des calculs du simulateur actuel "Indépendant".
La présentation du simulateur est proche de celle de l'assistant "Détermination des charges sociales déductibles" (les questions sont posées avant d'obtenir le résultat)

1) Questions à poser
- Date de radiation ? (permet le calcul des cotisation sur l'année incomplète N)
- Impôt sur le revenu ou impôt sur les sociétés ?
- Si impôt sur le revenu : 
                      - Chiffre d'affaires (année N)
                      - Charges (année N)
                     
- Si impôt sur les sociétés : 
                        - Rémunération totale (année N)
                                   
2) Calculer les cotisations à partir du paramétrage par défaut du simulateur "Indépendant"

3) Afficher le résultat 

"Total des cotisations à devoir après cessation d'activité" : montant en € = Cotisations année N sur nombre de mois travaillés en année N jusqu'à la date de radiation 

4) Affiner le résultat à partir des questions complémentaires impactant le montant des cotisations sociales (simulateur actuel "Indépendant")

- Nature de l'activité ?
- Régime micro-fiscal ?
- Date d'immatriculation ?
**_**A compléter**_**

Le coût de cessation d'activité se met à jour automatiquement au fur et à mesure des réponses aux questions

**Documentation :** 
https://www.urssaf.fr/accueil/services/services-independants/cessation-activite.html
 
```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/mon-entreprise/issues/2988
- [ ] https://github.com/betagouv/mon-entreprise/issues/2987
- [x] Cessation d'activité - ajouter règles sur durée affiliation (+ ou - 90 jours)
- [ ] https://github.com/betagouv/mon-entreprise/issues/3180
- [ ] https://github.com/betagouv/mon-entreprise/issues/1706
```

**Comment by glopezrios** [comment]
@VeroniqueR75 Cela me semble clair.

J'ai juste deux suggestions, à vérifier selon les différentes situations possibles:

Si impôt sur le revenu, enlever la possibilité de rentrer la "rémunération nette" (qui est justement calculée en tenant compte du montant de cotisations)

Si impôt sur les sociétés, enlever la possibilité de rentrer la "rémunération brute" (qui est, là aussi, calculée en tenant compte du montant de cotisations)

**Comment by VeroniqueR75** [comment]
Mises à jour à effectuer en plus de l'application des taux pour une année incomplète (retours réunion du 24/09) : 
Voir les pièces jointes
[simulateur cessation questions.docx](https://github.com/user-attachments/files/17750981/simulateur.cessation.questions.docx)
[simulateur cessation wording.pdf](https://github.com/user-attachments/files/17750982/simulateur.cessation.wording.pdf)
