### ISSUE TITLE
Mise à jour des taux début d'année

### ISSUE THREAD

**Issue by VeroniqueR75** [betagouv/mon-entreprise#3097]
Lister l'ensemble des taux qui sont mis à jour annuellement
```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/mon-entreprise/issues/3273
- [ ] https://github.com/betagouv/mon-entreprise/issues/3275
- [ ] https://github.com/betagouv/mon-entreprise/issues/3274
- [ ] [PLR] Mise à jour des valeurs CIPAV, CNAVPL, CARCDSF, CARPIMKO, CNBF
- [ ] https://github.com/betagouv/mon-entreprise/issues/3284
- [ ] https://github.com/betagouv/mon-entreprise/issues/3288
- [ ] https://github.com/betagouv/mon-entreprise/issues/3289
- [ ] Nouvelle version de modele-social
```

**Comment by liliced** [comment]
Cf https://github.com/betagouv/mon-entreprise/discussions/3041

**Comment by liliced** [comment]
- [ ] [IR] Mise à jour barème fiscal, déduction forfaitaire 10% et autres éléments de calcul de l'IR
