### ISSUE TITLE
Avancement des simulateurs pour les dirigeants

### ISSUE THREAD

**Issue by laem** [betagouv/mon-entreprise#497]
> Cette page listes les choses à faire pour améliorer les simulateurs des dirigeants

Mise à jour 9 avril, à faire avant la mise en prod des simulateurs individuels : 
- [x] debounce sur les saisies dans targetselection, pour la perf et pour le message d'inversion foirée
- [x] vérifier les calculs de l'AE, le net me semble élevé
- [x] mettre un message de pub et SEO sur embauche.beta --> on privilégie la migration complète vers mon-entreprise.fr
- [x] finir la traduction 

---------------

- [x] merger #489 dans `demo`

- [ ] Prendre les retours des tests utilisateur  [1ère session](https://github.com/betagouv/syso/wiki/Retours-utilisateurs-tests-Station-F-du-19-02-2019) et [2 ème session](https://github.com/betagouv/syso/issues/473)

- [x] charges sur les simulateurs

- [x] l'image est toujours en anglais

- [x]  Traduire la version finale du WarningMessage

# :hammer: Amélioration des calculs 

- [x] C'est du gachis de réserver le simulateur aux entreprises créées avant 2019. La simulation se place en 2019, donc la question de l'année d'activité nous donne l'année de création, dont on peut déduire les deux paramètres épineux :  voir #501 
- [ ] Implémenter les règles spécifiques des profession libérales 

Voir l'avertissement déclenché par le choix "libéral reglementé" dans le simulateur. CIPAV, PAM, CURPS, interdictions de l'AE.

- [ ] Ajouter un début de fiscalité des entreprises, en commençant par l'IS et dividendes pour les SAS; prélèvement libératoire d'IR pour les AE, ce qui implique une simulation de l'IR perso. 

- [ ] résoudre la note pour les conjoints collaborateurs en l'implémentant.

- [ ] intégration de la CVAE et CFE

# :gear:  Améliorations du moteur

- [x] réparer les aberrations de l'inversion (500 000 de CA qui peut apparaître sur le simul assimilé; cotisations minimales pour les indépendants, le CA est trop faible donc revenu négatif; sauts )

## Problèmes transverses

- [ ] Finir la refacto valeurs #481 , pour mieux visualiser les valeurs saisies (par exemple les pourcentages dans la formule "taux RSA") et permettre de répondre aux questions directement sur les pages /doc/règle 

- [ ] Tester la rapidité des calculs sur IE / machine peu puissante ? Est-ce du à l'inversion suite à la réforme des contrôles ?

## Améliorer les explications des calculs :framed_picture: 

- intégrer une vue calendrier : qu'est-ce qui est prélevé quel mois de l'année, et chacune des premières années. C'est une demande forte de BGE, surtout pour les indépendants.

- [ ]  améliorer le JSX des énums
- [ ] pour les pourcentages affichés comme arrondis, afficher un indicateur `~` et afficher une valeur plus précise au clic.
- [ ] améliorer le JSX d'une comparaison d'énums : surtout quand simulation en cours, le lecteur ne comprend pas, ça semble dédouble.
- [ ] Mieux afficher "désactivée par", notamment quand pas de données.
- [ ] Pour le barème continu, et les barèmes à multiplicateur en général, si multiple entier, `3 *`, sinon `110% *`
- [ ] ne pas afficher le taux final pour un barème simple de retraite à deux tranches

- [ ] Dans la variable [cotisations de l'indépendant](https://demo.mon-entreprise.fr/documentation/indépendant/cotisations) : Pour un PL est-il nécessaire d’afficher la Maladie 2 compte-tenu qu’il n’est pas redevable de cette cotisation même si l’affichage ci-dessous est indiqué si on clique sur Maladie 2?

Je pense que l'on peut répondre à ce problème en mettant tout ce qui concerne la maladie dans une variable maladie qui opérerait une `variations`

- [ ] Règles d'arrondis : je pense que ce n'est pas prioritaire pour une première version en ligne. Voir #490

**Comment by mquandalle** [comment]
Les simulateurs dirigeants sont en prod depuis un moment, mieux vaut gérer les points d'amélioration dans des issues dédiées.
