### ISSUE TITLE
Modifications au 1er janvier 2020

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#676]
J'ouvre une issue concernant les modifications de règles qui s'appliqueront le 1<sup>er</sup> janvier prochain.

* Loi PACTE
  - [x] Nouveaux seuils pour la fnal et la participation à l'effort de construction qui passent de 20 salariés à 50 https://www2.editions-tissot.fr/actualite/droit-du-travail/cotisations-sociales-du-changement-avec-la-loi-pacte
  - [x] Les règles concernant les seuils sociaux sont simplifiées, il n'y en a plus que trois : 11, 50 et 250 salariés, et les règles de calcul sont harmonisées https://www.journaldunet.com/management/ressources-humaines/1442847-loi-pacte-ce-qui-va-changer-pour-les-seuils-sociaux
    On pourra en profiter pour simplifier la question concernant l'effectif de l'entreprise, et proposer différent choix (moins de 11, moins de 50, moins de 250, plus de 250) plutôt que de demander inutilement l'effectif exact à l'utilisateur. On pourra aussi ajouter une note d'information sur le passage des seuils.
* PLF, PLFSS
  * CDD
    - [ ] Système de bonus-malus pour les entreprises de plus de 11 salariés dans 7 secteurs d'activité #573
    - [x] Taxe forfaitaire de 10€ sur les CDD d'usage pour limiter l’usage de contrats très courts
    - [ ] Adaptation de la réduction générale pour exclure le système de bonus-malus sur les cotisations chômage http://www.assemblee-nationale.fr/15/pdf/projets/pl2296-ei.pdf#page=28
  - [x] Nouveau barème de l'IR http://www.assemblee-nationale.fr/15/pdf/projets/pl2272.pdf#page=34
  - [x] Réduction du montant de la décote
  - [x] Suppression de la réduction d'impôt Article 197 I 4 b https://www.legifrance.gouv.fr/affichCodeArticle.do?idArticle=LEGIARTI000038687475&cidTexte=LEGITEXT000006069577&dateTexte=20190608 (il ne me semble pas qu'on l'implémente)
  - [x] Nouveaux barèmes taux neutre http://www.assemblee-nationale.fr/15/pdf/projets/pl2272.pdf#page=35
  * ~Baisse du taux normal d'impôt sur les sociétés à 28%~ repoussé pour raisons budgétaires
  - [ ] Généralisation de l'aide « emplois francs »
  - [ ] Plafonnement de la déduction forfaitaire spécifique https://github.com/betagouv/mon-entreprise/issues/679#issuecomment-537396381
* Revalorisations
  - [x] Plafond de la sécurité sociale
  - [x] SMIC
  - [x] Taux AT/MP
- [x] Réforme 100% santé. Impact sur le prix des mutuelles ?
  A priori pas d'impact sur le prix des mutuelles.
- [x] Rabotage de l'ACRE #698

**Comment by johangirod** [comment]
> On pourra en profiter pour simplifier la question concernant l'effectif de l'entreprise, et proposer différent choix (moins de 11, moins de 50, moins de 250, plus de 250) plutôt que de demander inutilement l'effectif exact à l'utilisateur

Tout à fait, je m'était déjà fait la reflexion :)

**Comment by mquandalle** [comment]
Plafond de la sécurité sociale 2020 :
- valeur mensuelle : 3428 euros
- valeur journalière : 189 euros

https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000039440180

**Comment by mquandalle** [comment]
- [ ] Les valeurs des points des systèmes de retraite ainsi que les barèmes pour valider les trimestres sont aussi revalorisés
