### ISSUE TITLE
Réparer le tracking

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#735]
- [ ] Les inputs transmettent les valeurs sans throttle. Si un utilisateur saisi '1300' on track '1', '13', '130' et '1300'.
- [x] Changer la définition du "goal" : `Commence une simulation` pour correspondre à l'évenement `targetSelected`. On peu ainsi avoir plusieurs simulation par session (en changeant le salaire). 
- [ ] Différencier le tracking pour chaque simulateur

**Comment by johangirod** [comment]
Fixed by #1414
